name: Evaluate Predictions

on:
  pull_request_target:
    types: [opened, edited, reopened]

env:
  PA3_PASSWORD: ${{ secrets.PA3_PASSWORD }}
  FOO: ${{ secrets.FOO}}

jobs:
  evaluate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install GnuPG
        run: |
          sudo apt-get update
          sudo apt-get install gnupg
      - name: print environment
        run: printenv
      - name: Echo sth random
        run: echo "$FOO" "$PUBLIC_REPO_VARIABLE"
      - name: Decrypt ground truth file
        run: |
          echo "${{ secrets.PA3_PASSWORD }}" | gpg --quiet --batch --yes --decrypt --passphrase-fd 0 --output ground_truth.tsv ground_truth_encrypted.tsv
      - name: Install Python dependencies
        run: "pip install -r requirements.txt"
      - name: Evaluate predictions and post score
        run: "python evaluate.py predictions.tsv ground_truth.tsv"
      - name: Remove all TSVs
        run: "rm ground_truth.tsv"
